### ISSUE TITLE
Not compatible with Blog Plugin

### ISSUE THREAD

**Issue by drtzack** [rainlab/sitemap-plugin#11]
It's not showing blog posts and categories.

**Comment by tplessis** [comment]
+1
There's trouble with dynamic contents. Slugs are replaced by "default" value.

**Comment by drtzack** [comment]
Blog categories is fixed but blog posts are still same.

http://www.talhadurmus.com/sitemap.xml

**Comment by drtzack** [comment]
It adds "default" to end.

~~~
<url>
<loc>http://www.talhadurmus.com/default</loc>
<lastmod>2015-08-13T16:17:35+03:00</lastmod>
<changefreq>always</changefreq>
<priority>0.5</priority>
</url>
~~~

**Comment by drtzack** [comment]
Blog categories is fixed but blog posts still same.

Blog post slugs are still replaced by "default" value
