### ISSUE TITLE
Exception call to undefined method Definitiionitem::resolveattribute

### ISSUE THREAD

**Issue by robballantyne** [rainlab/sitemap-plugin#12]
Call to undefined method RainLab\Sitemap\Classes\DefinitionItem::resolveAttribute()
/var/www/html/*myproject*/modules/backend/Widgets/Form.php line 917
October build 220

 917: list($model, $attribute) = $this->model->resolveAttribute($htmlArray);

**Comment by daftspunk** [comment]
Fixed in Build 221
