### ISSUE TITLE
Error: Call to undefined method Backend\Classes\BackendHelper::redirect()

### ISSUE THREAD

**Issue by justanne** [rainlab/sitemap-plugin#16]
After installing and clicking the Sitemap link under settings shows me this error:

![exception2](https://cloud.githubusercontent.com/assets/1003597/7294474/51a083a2-e9e0-11e4-87e9-1f4f5bc71443.jpeg)

URL is: /backend/rainlab/sitemap/definitions

**Comment by oleg-schelkunov** [comment]
I've had same issue when i was using an old build of October. I've added this method manually in a class as hotfix, and upgraded to RC later.

**Comment by oleg-schelkunov** [comment]
Also, you can view the changes what have made the plugin unusable on pre-rc versions: cb1dcafb57009b6f368431ec7dc2adf195ea1c47

**Comment by justanne** [comment]
Alrighty, thanks!
