### ISSUE TITLE
sitemap.xml is empty?

### ISSUE THREAD

**Issue by json-wong** [rainlab/sitemap-plugin#18]
I added some data for sitemap. but the sitemap content is empty of http://domain/sitemap.xml

That page content displayed without I added data, like this:

`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd"/>`

How can I fix this problem?

**Comment by fiberit** [comment]
Same problem here !

**Comment by json-wong** [comment]
@daftspunk We need help.

**Comment by daftspunk** [comment]
Need some more info please, the sitemap plugin works for me. How can I replicate this issue?

**Comment by json-wong** [comment]
Hi @daftspunk 

I don't know why this happened, it working in a new installation version of OctoberCMS, just don't work in my existing instance. 

That details please refer to the attached picture.

I was added some data in sitemap page, but there are not displayed on the frontend page.

![20150707144512](https://cloud.githubusercontent.com/assets/275036/8540332/44de7bee-24b7-11e5-86e9-e1d57989bb56.png)
![20150707144408](https://cloud.githubusercontent.com/assets/275036/8540333/48b99a5a-24b7-11e5-8de7-a3e46bb26f8a.png)

**Comment by daftspunk** [comment]
If you view the source of that URL does it show anything different? Sometimes the preview doesn't show everything.

Does it happen on a clean install?

**Comment by json-wong** [comment]
@daftspunk The source page is also not show those contents. 

I guess that plugin is not incomplete, this problem does not occur when I used a new OctoberCMS.

Is there any way to reinstall that plugin of sitemap on my existing instance? I have a lot of data in that instance, so if I use a new OctoberCMS then need to transfer a lot of data.

**Comment by json-wong** [comment]
OK, I found that solution, I made reference to #14 and modify the `route.php` of sitemap plugin, that sitemap page can display those contents.

Why this fix has not been updated through system updates? This issue should be common when installed multiple themes.

**Comment by daftspunk** [comment]
Should be well and truly available by now 😄
