### ISSUE TITLE
Hidden static pages 

### ISSUE THREAD

**Issue by shrpne** [rainlab/sitemap-plugin#19]
When use "All static pages" type
If static page is `Hidden in navigation`, than it and all childs will not appear in sitemap.
If static page is `Hidden` and not `Hidden in navigation`, than it will appear in sitemap.

I think only `Hidden` parameter should affect visibility of static pages in sitemap, and it should not affect childs.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
