### ISSUE TITLE
repeated url domain when adding problog tag on sitemap

### ISSUE THREAD

**Issue by laics1984** [rainlab/sitemap-plugin#27]
Noticed that the url under <log> tag has repeated domain when i add problog tag on sitemap via plugin.

The <loc> is 

domain.com/domain.com/blog/tag

How to remove the repeated domain.com?

**Comment by gerasart** [comment]
i have analog problum(((

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
