### ISSUE TITLE
Fails if php-xml not installed

### ISSUE THREAD

**Issue by woganmay** [rainlab/sitemap-plugin#39]
If the plugin is installed on a server that does not have the php-xml installed, it will just fail with an exception, that it cannot find the DOMDocument class.

```
Class 'DOMDocument' not found
.../plugins/rainlab/sitemap/models/Definition.php line 156
```

I resolved it by installing php7.0-xml on my instance:

```
sudo apt-get install php7.0-xml
```

Would be nice if the plugin could check for that module's existence before installing.

**Comment by daftspunk** [comment]
Or at the very least this should be included in the readme / documentation

**Comment by abass** [comment]
Thank you @woganmay this fixed the error for me!

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
