### ISSUE TITLE
Sitemap Returning 404 Even Though It's Live

### ISSUE THREAD

**Issue by rlaborce** [rainlab/sitemap-plugin#41]
Hi,

Even though the sitemap is live, an error displays citing a 404. I submitted to Google's Webmaster and it too also displays a 404 error.

http://canadoorsystems.com/sitemap.xml

<img width="1445" alt="screen shot 2016-10-11 at 9 35 08 am" src="https://cloud.githubusercontent.com/assets/15614624/19272303/1192166a-8f96-11e6-84a7-b231b9fad292.png">

**Comment by daftspunk** [comment]
Unable to replicate this. The /sitemap.xml file is returning status code 200 on my end.
