### ISSUE TITLE
Is it possible to use custom post types (automatically) in the sitemap plugin?

### ISSUE THREAD

**Issue by maartenmachiels** [rainlab/sitemap-plugin#51]
The sitemap plugin supports the Blog- and Forum plugin out of the box. I was wondering if it's at all possible to extend this functionality to custom plugins. 

My plugin consists of a list of items, each one having their own url. It would be nice if I could get my items into the sitemap without having to define them manually per item (because items will be added / renamed / removed). 

The documentation seems to stay a little vague about this. Is this possible and if so, is there a working example available somewhere?

Thanks in advance.

**Comment by LukeTowers** [comment]
Yes, it uses the RainLab.Pages events for defining menu items. Look at the blog plugin code to figure out how to implement it yourself. Ideally then add to the documentation to help other people in the future.

**Comment by maartenmachiels** [comment]
Beste,

We zijn er even tussenuit van 25 t.e.m. 29 oktober.
We behandelen je mailtje met plezier op maandag 30 oktober.

Mvg,

Maarten Machiels
