### ISSUE TITLE
XML declaration allowed only at the start of the document

### ISSUE THREAD

**Issue by billrafferty** [rainlab/sitemap-plugin#59]
There is an immediate line break at the start of the rendered XML file which causes an error on line 2 at column 6: XML declaration allowed only at the start of the document.

This behaviour is in our production environment but not in development with apparently same config and both on the latest version of the plugin. Have tried looking at plugin code and can't see why this is happening or how to fix it.

The rest of the sitemap.xml file is correct but not being read as failing before rendering any of the page up to the first error.

**Comment by LukeTowers** [comment]
That sounds like an environment configuration issue to me; can you reproduce this on Homestead with a fresh install of October and the plugin?

**Comment by billrafferty** [comment]
I've looked at other xml and html pages on production, all exhibit the same initial CarriageReturn/LineFeeds on the first line so I agree it's outside this plugin and most likely a environment condition. Apologies for the posting in error. Now just need to figure out whats causing the problem...

**Comment by LukeTowers** [comment]
No worries @billrafferty. Feel free to post a follow up when you figure it out!

**Comment by didiervassout** [comment]
Hello @billrafferty I've exactly the same issue. Did you figure out how to resolve this?
