### ISSUE TITLE
Error while accessing sitemap.xml

### ISSUE THREAD

**Issue by worldofsmarty** [rainlab/sitemap-plugin#60]
Hello,

We have the sitemap plugin installed for a few years now in our website. But recently it started behaving weirdly. The error shown in the below screenshot appears very regularly.
![sitemap-error](https://user-images.githubusercontent.com/5152491/44079068-c2db952c-9fc5-11e8-8617-80f88393f96f.png)

Once we open the sitemap menu/link from the settings section, we will be able to see the sitemap.xml file correctly. But after some 3 to 4 hours of time again it will display the same error as shown in the first screenshot.

After accessing the sitemap page from the settings section. It will revert back to normal.
![image](https://user-images.githubusercontent.com/5152491/44079399-9252ad36-9fc6-11e8-9768-26023322d3e1.png)

![image](https://user-images.githubusercontent.com/5152491/44079377-7a8f74c2-9fc6-11e8-839d-c7684aa8d147.png)

**Comment by LukeTowers** [comment]
@worldofsmarty looks like it might have something to do with your plugins/vdomah/blogviews/Plugin.php line 60. Check to see if that's the issue by disabling the plugin first.

**Comment by kevinvermeulenn** [comment]
Hi! I have the same issue. 
Any update regarding this issue?

**Comment by LukeTowers** [comment]
@kevinvermeulenn did you read my comment?

**Comment by kevinvermeulenn** [comment]
@LukeTowers, Yes I did. I’ve disabled the plugin. Unfortunately, it does not work.

**Comment by LukeTowers** [comment]
@kevinvermeulenn you're going to have to be more specific than that. Did you try emptying the cache after disabling the plugin? What error appeared on the screen?

**Comment by kevinvermeulenn** [comment]
@LukeTowers 

Well, right now. I've disabled the plugin Views and deleted my october and browser cache.
If you see the page: https://www.kvntravel.nl/sitemap.xml, it is not working correctly (see attachment as well). 

![image](https://user-images.githubusercontent.com/13196012/45628835-395ba180-ba95-11e8-9376-d7ad178b24d2.png)

Does this help?

**Comment by LukeTowers** [comment]
@kevinvermeulenn yes, I suggest you try reading the error messages instead of panicking :)

The error you're getting is that `Class name is not registered for the component "views"`, and it tells you to "Check the component plugin". One of your pages still has the `views` component on it which previously would have been provided by the plugin in question, you need to remove that plugin's components from the pages so that the pages aren't trying to load a non-existent component.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
