### ISSUE TITLE
Google indexes the sitemap.xml url in search results

### ISSUE THREAD

**Issue by zlobec** [rainlab/sitemap-plugin#61]
Hey,

It seems that Google indexes the sitemap.xml url and displays it in the search results.

Is it possible to include the tag **X-Robots-Tag: noindex** in the HTTP response?
See more info: https://webmasters.stackexchange.com/questions/62978/prevent-xml-sitemaps-from-showing-up-in-google-search-results

Regard,
Darjan

**Comment by LukeTowers** [comment]
@zlobec feel free to submit a PR to do so!

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
