### ISSUE TITLE
Sitemap returning 404 status code

### ISSUE THREAD

**Issue by drmzio** [rainlab/sitemap-plugin#70]
Referencing issue #41 because I'm also having a problem with the `/sitemap.xml` returning 404 status code even though it exists.

Sitemap |
--- |
![](https://cl.ly/015f7aee7207/%255B45bb1562d57653697eeb1fdaea3b72dc%255D_Image%2525202019-11-17%252520at%2525209.03.34%252520PM.png) |
URL: https://october-news.com/sitemap.xml |

Might have to force a 200 status code in the response.

https://github.com/rainlab/sitemap-plugin/blob/41fdc4385a5f5b0910133d4713e492e50f5fb844/routes.php#L20-L22

**Comment by bennothommo** [comment]
@drmzio It could potentially be a server configuration issue. I get 200 on some of my client websites:

https://www.morleycanvas.com.au/sitemap.xml
https://summerstar.com.au/sitemap.xml

**Comment by drmzio** [comment]
Ok I think I found the culprit. Seems like Forge adds these lines to my Nginx configuration and commenting them out solves the 404 issue 👍 

![](https://cl.ly/a3aa41e822af/Image%2525202019-11-17%252520at%2525209.32.22%252520PM.png)
