### ISSUE TITLE
Seeing output I don't believe should render at the top of the output xml file

### ISSUE THREAD

**Issue by SplicedWeb** [rainlab/sitemap-plugin#80]
The text output that shows in the top of the sitemap is:
// Catch errors if signal is already set by user agent or other extension try { Object.defineProperty(navigator, 'globalPrivacyControl', { value: false, enumerable: true }) // Remove script tag after execution document.currentScript.parentElement.removeChild(document.currentScript) } catch (e) {}

**Comment by bennothommo** [comment]
@SplicedWeb that appears to be code that is being injected by your browser, or perhaps another plugin. That isn't being generated by the Sitemap plugin. You'll need to audit your plugins (perhaps disable them one by one) and see if any of them are inserting that code.
