### ISSUE TITLE
Software updating problem, database (MariaDB) doesn't want to update

### ISSUE THREAD

**Issue by patimio66** [rainlab/sitemap-plugin#82]
Trying to update from 1.0.1 to 1.0.9.

![image](https://user-images.githubusercontent.com/78798236/127619519-6393dfcd-a664-4975-a8c5-7a13f560010f.png)

And here's the bug showing after a few seconds.
Update failed
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'rainlab_sitemap_definitions' already exists (SQL: create table `rainlab_sitemap_definitions` (`id` int unsigned not null auto_increment primary key, `theme` varchar(65535) null, `data` mediumtext null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB)

Trying again doesn't help at all, same error shows up. Tried also to remove the table, and this showed up:
Update failed
SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'theme' used in key specification without a key length (SQL: alter table `rainlab_sitemap_definitions` add index `rainlab_sitemap_definitions_theme_index`(`theme`))

**Comment by daftspunk** [comment]
You will need to reinstall the plugin from scratch and delete all indexes and tables that are prefixed with `rainlab_sitemap_*`. The second error shows a rogue index is still hanging around. If you need further assistance with this, and faster response times, send an email to hello@octobercms.com

Thanks
