### ISSUE TITLE
Sitemap is empty, changes aren't saved

### ISSUE THREAD

**Issue by Chinyoka1** [rainlab/sitemap-plugin#84]
I tried to add the sitemap definitions in the backend, but they aren't saved to the database, so when I reload the page, it's empty again. On http://domain/sitemap.xml, all I see is this.
![grafik](https://user-images.githubusercontent.com/59474009/137121594-274d1a0c-5b42-4441-a687-d35afa1b4e46.png)

I read the other issues with the same problem, but I couldn't find a working solution.

**Comment by daftspunk** [comment]
Thanks for the report @Chinyoka1

This should be fixed in v1.1.1 of this plugin. Please update and try again
