### ISSUE TITLE
Sitemap won't open, instead downloads source file

### ISSUE THREAD

**Issue by chocolata** [rainlab/sitemap-plugin#86]
Hi, 

I might be overlooking something, but in my setup (over multiple sites) when I navigate to https://domain.com/sitemap.xml, the enclosed file is just being downloaded instead of showing the actual sitemap:

![image](https://user-images.githubusercontent.com/3584586/147767795-3a0ae6cf-e5d5-42f0-8c46-f513bc0393a6.png)

I'm using October CMS v2.1.24 and the Rainlab Sitemap plugin version 1.1.1. I'm using a mirrored setup. I've followed the Nginx instructions you provided here: 
[https://docs.octobercms.com/2.x/setup/deployment.html#nginx-configuration](https://docs.octobercms.com/2.x/setup/deployment.html#nginx-configuration)

Can you kindly let me know how we can solve this? I'd be happy to provide more details.

Kind regards.

**Comment by TimFoerster** [comment]
Can you post your nginx domain configuration file?
I am unable to reproduce the problem. It works fine for me (nginx/1.21.1).

**Comment by chocolata** [comment]
Hi Tim, thanks for your answer. Just checked - removing the nginx configuration seems to have no effect, the problem still persists. These are the directives I'm using:

```
location ~* \.(js|jpg|jpeg|gif|png|css|tgz|gz|rar|bz2|doc|pdf|ppt|tar|wav|bmp|rtf|swf|ico|flv|txt|woff|woff2|svg)$ {
	etag on;
	if_modified_since exact;
	add_header Pragma "public";
	add_header Cache-Control "max-age=31536000, public";
}

location httpdocs {
	# Let October CMS handle everything by default.
	# The path not resolved by October CMS router will return October CMS's 404 page.
	# Everything that does not match with the whitelist below will fall into this.
	rewrite ^/.*$ /index.php last;
}

# Pass the PHP scripts to FastCGI server
location ~ ^/index.php {
	# Write your FPM configuration here

}

# Whitelist
location ~ ^/favicon\.ico { try_files $uri /index.php; }
location ~ ^/sitemap\.xml { try_files $uri /index.php; }
location ~ ^/robots\.txt { try_files $uri /index.php; }
location ~ ^/humans\.txt { try_files $uri /index.php; }

# Block all .dotfiles except well-known
location ~ /\.(?!well-known).* { deny all; }

## Let nginx return 404 if static file not exists
location ~ ^/storage/app/uploads/public { try_files $uri 404; }
location ~ ^/storage/app/media { try_files $uri 404; }
location ~ ^/storage/app/resources { try_files $uri 404; }
location ~ ^/storage/temp/public { try_files $uri 404; }

location ~ ^/modules/.*/assets { try_files $uri 404; }
location ~ ^/modules/.*/resources { try_files $uri 404; }
location ~ ^/modules/.*/behaviors/.*/assets { try_files $uri 404; }
location ~ ^/modules/.*/behaviors/.*/resources { try_files $uri 404; }
location ~ ^/modules/.*/widgets/.*/assets { try_files $uri 404; }
location ~ ^/modules/.*/widgets/.*/resources { try_files $uri 404; }
location ~ ^/modules/.*/formwidgets/.*/assets { try_files $uri 404; }
location ~ ^/modules/.*/formwidgets/.*/resources { try_files $uri 404; }
location ~ ^/modules/.*/reportwidgets/.*/assets { try_files $uri 404; }
location ~ ^/modules/.*/reportwidgets/.*/resources { try_files $uri 404; }

location ~ ^/plugins/.*/.*/assets { try_files $uri 404; }
location ~ ^/plugins/.*/.*/resources { try_files $uri 404; }
location ~ ^/plugins/.*/.*/behaviors/.*/assets { try_files $uri 404; }
location ~ ^/plugins/.*/.*/behaviors/.*/resources { try_files $uri 404; }
location ~ ^/plugins/.*/.*/reportwidgets/.*/assets { try_files $uri 404; }
location ~ ^/plugins/.*/.*/reportwidgets/.*/resources { try_files $uri 404; }
location ~ ^/plugins/.*/.*/formwidgets/.*/assets { try_files $uri 404; }
location ~ ^/plugins/.*/.*/formwidgets/.*/resources { try_files $uri 404; }
location ~ ^/plugins/.*/.*/widgets/.*/assets { try_files $uri 404; }
location ~ ^/plugins/.*/.*/widgets/.*/resources { try_files $uri 404; }

location ~ ^/themes/.*/assets { try_files $uri 404; }
location ~ ^/themes/.*/resources { try_files $uri 404; }
```

**Comment by TimFoerster** [comment]
are you sure that this is the correct file?

Your php handler is empty
```
# Pass the PHP scripts to FastCGI server
location ~ ^/index.php {
	# Write your FPM configuration here

}

``` 

Do you use fpm or apache?

**Comment by chocolata** [comment]
Hi Tim,

I'm using a Plesk server and cannot access the nginx configuration file directly. I pasted the above code into the additional nginx directives field:

![image](https://user-images.githubusercontent.com/3584586/147916114-59ae9cfb-7811-4c3c-ac63-4851c7daa5af.png)

I'm using FastCGI served by Apache.
![image](https://user-images.githubusercontent.com/3584586/147916170-f6e5b68a-5250-4637-a758-1b44cda53be7.png)

Removing the directives from that field doesn't change anything however.

Do you have any recommendations that I should try?

**Comment by daftspunk** [comment]
Hi @chocolata,

There is caused by some nginx configuration, out of reach, that forces the .xml suffix in the URL to display with plaintext encoding. This is unique to Plesk and you'd need to contact your hosting provider for support with this. However, using this Plesk tool, it is best to stick with Apache, that is significantly faster than their Nginx implementation anyway.

I hope this helps!

**Comment by chocolata** [comment]
Hi @daftspunk 

Thanks for your views. Just to verify - I checked some of my sites that are still running October CMS v1, and there the sitemaps do download correctly. For example, I just checked a site running build 469, with the Sitemap plugin v1.0.1, running on the same server with the same configuration as my newest sites, and there the sitemap does show correctly. I'd be happy to provide additional details. 

Thanks aswel for your views on nginx vs Apache. Will definitely look in to it.

**Comment by TimFoerster** [comment]
@chocolata  do you use the same `.htaccess` file?

**Comment by daftspunk** [comment]
> is it still possible that it is related to a Plesk issue?

Based on the observations, this is very likely to be caused by web server configuration. When accessing the sitemap URL, the PHP engine does not even start, it just delivers the entry point index.php contents as if it were a static file. Look at comparing the configuration of the v1 site and v2 site side by side to see if you notice any differences.

**Comment by chocolata** [comment]
Hi - thanks for your follow-up. I've just checked thoroughly, but the configuration is completely the same between the v1 and v2 install apart from the mirroring (only v2 is mirrored). The v2 sites haven't migrated to another server / did not change configuration... Update to v2 was done in place. I'm curious to know if anyone else has experienced this issue. In any case I'll keep looking and report back if I figure something out.

**Comment by chocolata** [comment]
@daftspunk Just to check: is there any way to undo the mirroring to test out if that could be the issue in conjunction with the webserver config?

**Comment by daftspunk** [comment]
I'm not too familiar with Plesk, sorry.

**Comment by chocolata** [comment]
Hi, just wanted to let you guys know that in a non-mirrored setup the sitemap.xml file loads without problems. Can you let me know which steps to follow to undo a mirrored setup until we find the solution?

**Comment by chocolata** [comment]
Hi, for those Plesk users who are also seeing this issue in a mirrored setup: I think I've found a solution. 

In the nginx settings of your subscription, scoll to `Serve static files directly by nginx`, tick the box and enter `xml` as the only entry.
![image](https://user-images.githubusercontent.com/3584586/155499521-e2822eb9-8062-470e-95d4-9e0718accc07.png)

You might have to disable nginx caching and re-enable it for it to take, but this seems to work for me. In the end it didn't matter if the subscription was set up as `FastCGI application served by Apache`, or `FPM application served by Apache`, or `FPM application served by nginx`.

I don't really understand the inner workings of this. If anyone has any other views on this topic, be sure to let me know, I'm very interested in finding out any side effects of this solution. At first glance, this doesn't seem to have any other effects, but I will keep you posted if I find something.

**Comment by daftspunk** [comment]
> In the nginx settings of your subscription, scoll to Serve static files directly by nginx, tick the box and enter xml as the only entry.

Interesting. This seems like the reverse of what we want. But. If it works, it works.
