### ISSUE TITLE
Error on sitemap.xml 

### ISSUE THREAD

**Issue by roojai** [rainlab/sitemap-plugin#89]
I am running Octobercms 2.2.25 and plugin version 1.2.0 and I am getting an error on the sitemap.xml whether I add items to the site map or even if it is blank.

The error is 

This page contains the following errors:
error on line 2 at column 6: XML declaration allowed only at the start of the document
Below is a rendering of the page up to the first error.

..and nothing else follows

**Comment by roojai** [comment]
I worked through all the plugins on my site and found it was one of my own plugins that was causing the problem. I had a routes.php file that had the opening <?php on line 2 instead of line 1 and this was causing the issue. Sorry for raising a non-existent issue!

**Comment by daftspunk** [comment]
Great! Glad you got it sorted. Thank you for reporting back
