### ISSUE TITLE
SitemapHandler::sitemap() should not be called statically

### ISSUE THREAD

**Issue by jan-vince** [rainlab/sitemap-plugin#91]
Error after update from Sitemap plugin 1.2.0 to 1.2.2:

`ErrorException: Non-static method RainLab\Sitemap\Handlers\SitemapHandler::sitemap() should not be called statically in /vendor/laravel/framework/src/Illuminate/Routing/Route.php:197`

OC version 476.

**Comment by daftspunk** [comment]
Should be fixed by 4eee957c87160f7dc64d730476cd5c81d46e0e1b

Please update to v1.2.3 and try again

**Comment by jan-vince** [comment]
Hi @daftspunk,

it works, thanks!

PS: v1.2.3 is not available through Marketplace yet.
