### ISSUE TITLE
Show dynamic parameters for pages where are used models made in Builder plugin

### ISSUE THREAD

**Issue by jjezik82** [rainlab/sitemap-plugin#93]
Hi there, I have problem showing dynamic parameters in url's for pages that are using models made in Builder plugin.
Example page : 

`url = "/product/:slug"`
`layout = "default"` 
`title = "Product"` 
`==` 
`<?php `
`use Codeupp\Client\Models\Product; `
`  function onStart(){ `
`    $slug = $this->param('slug'); `
`    $product = Product::where('slug', $slug)->first(); `
`    if(!$product){ `
`      return Redirect::to('/'); `
`    }` 
`    $this['product'] = $product; `
`  } `
`?> `
`==`

and sitemap object for this url looks like this:

`<url>`
`<loc>https://client.com/product/default</loc>`
`<lastmod>2023-06-09T14:07:43+00:00</lastmod>`
`<changefreq>monthly</changefreq>`
`<priority>0.6</priority>`
`</url>`

Is there a way for me to make this work somehow, or is my approach wrong here? Thanks.

**Comment by daftspunk** [comment]
Hey @jjezik82 

In your sitemap page make sure the URL has the parameter passed to it, something like this.

```
<loc>{{ 'product-page'|page({ product.id }) }}</loc>
```
