### ISSUE TITLE
Error on /sitemap.xml page after install

### ISSUE THREAD

**Issue by yellotra** [rainlab/sitemap-plugin#94]
Error on /sitemap.xml page after install

**Comment by yellotra** [comment]
It seems that plugin does not work with  October 3.3 version

**Comment by daftspunk** [comment]
What error are you getting?

Yes, for 3.3 we would recommend using the sitemap implementation that comes with the demo theme. Take a look at the sitemap file here:

app/blueprints/demo/site/sitemap.yaml
