### ISSUE TITLE
It doesn't open sitemap.xml

### ISSUE THREAD

**Issue by asadmay** [rainlab/sitemap-plugin#97]
![Screenshot_1](https://github.com/user-attachments/assets/5ce79d82-7338-4545-892f-6a03707cc839)
When trying to open sitemap.xml in which I added 3 cms pages, this error comes out through the plugin. How can I fix it?

**Comment by daftspunk** [comment]
Hi @asadmay 

Make sure the active theme set in your configuration exists. It looks like the theme is configured to a directory that no longer exists.

I hope this helps!

**Comment by asadmay** [comment]
The problem is that when the demo theme is deleted and when the demo plugin is deleted, an error appears (they say there is no such plugin) that there is no activated theme, although it is enabled, but for some reason the demo remains active, which is deleted.

**Comment by darhmedia** [comment]
The solution: In such cases, you need to modify the env file to switch from "demo" to the activated theme, and then the sitemap.xml will load without errors.
